language: java
jdk:
  - openjdk11

# Configuración específica de Java
before_install:
  - chmod +x gradlew

# Comandos a ejecutar antes de la prueba
before_script:
  - ./gradlew assemble

# Comandos de prueba
script:
  - ./gradlew test

