language: java
jdk:
  - openjdk11

script:
  - javac -cp .:./lib/junit-4.12.jar:/usr/share/java/hamcrest-core-1.3.jar repository/PruebaConexion.java
  - java -cp .:./lib/junit-4.12.jar:/usr/share/java/hamcrest-core-1.3.jar org.junit.runner.JUnitCore repository.PruebaConexionTest
